### ISSUE TITLE
ABOUT skel-panels...

### ISSUE THREAD

**Issue by Burhh** [adam-stokes/hexo-theme-striped#6] opened 2014-05-18 01:59 UTC
the theme is very nice, but I met a problem:after I deleted the default index.html,run hexo g.  hexo will generate a index.html. however,the console.log of the index.html show "Uncaught TypeError: undefined is not a function skel-panels.min.js:31".I try to solve it and find the bug line.  b.cache.pageWrapper.css("position", "relative").css("left", "0").css("right", "0").css("top", "0")._skel_panels_init();
It led to my Android phone can not display the page correctly
could you help me ?

**Comment by adam-stokes** [comment] 2014-05-18 02:07
thanks, will take a look this weekend

**Comment by adam-stokes** [comment] 2014-08-10 00:31
I believe this is fixed now, can you test?

**Comment by helvalius** [comment] 2014-08-13 21:20
This is still open. I have the same issue with a fresh installation. Seems to be related to https://github.com/n33/skelJS/issues/31

**Comment by adam-stokes** [comment] 2014-08-13 21:24
update: ok i reproduced the problem, will try to have a fix soon

**Comment by adam-stokes** [comment] 2014-08-15 23:04
not sure why the skel-panel.js is still throwing errors, looking at that bug referenced it is saying to not load jquery twice (which its not) still looking into it

**Comment by rainoxu** [comment] 2014-09-15 07:59
I met the same problem...

**Comment by HarryAdney** [comment] 2014-09-15 14:37
Same here. Seems to relate to a Twitter widget feed - which aint feedin'!

**Comment by adam-stokes** [comment] 2014-09-15 15:23
ok ill look into the twitter feed widget

**Comment by HarryAdney** [comment] 2014-09-15 18:26
Cheers Adam.

Best regards,

Martin Dimmock
Owner,
HarryAdney Internet Services

Tel: 01969 662794
Email: martin@harryadney.co.uk
Web: http://harryadney.co.uk

http://www.peopleperhour.com/hire/me/1709457307/45006?next=http%3A%2F%2Fwww.peopleperhour.com%2Ffreelancer%2Fmartin%2Fweb-host-domain-name-registrar-we%2F45006

http://customer.heartinternet.uk/aff.cgi?entry=TpX6bAcwY3UTTrgMm_vk/w&landing=web_hosting

http://www.linkedin.com/in/martindimmock

**Comment by adam-stokes** [comment] 2014-09-15 20:28
Ok, think its fixed now

**Closed as completed** 2014-09-15 20:28 UTC

**Comment by HarryAdney** [comment] 2014-09-16 09:33
Hi Adam,

It works fine on mobile but not on desktop. I suspect it's my CSS at fault
on the desktop.

Many thanks.
ᐧ

Best regards,

Martin Dimmock
Owner,
HarryAdney Internet Services

Tel: 01969 662794
Email: martin@harryadney.co.uk
Web: http://harryadney.co.uk

http://www.peopleperhour.com/hire/me/1709457307/45006?next=http%3A%2F%2Fwww.peopleperhour.com%2Ffreelancer%2Fmartin%2Fweb-host-domain-name-registrar-we%2F45006

http://customer.heartinternet.uk/aff.cgi?entry=TpX6bAcwY3UTTrgMm_vk/w&landing=web_hosting

http://www.linkedin.com/in/martindimmock

**Comment by adam-stokes** [comment] 2014-09-16 12:55
@HarryAdney are you able to attach a screenshot of the desktop version that isn't working?

**Comment by HarryAdney** [comment] 2014-09-16 14:41
Actually, I've just checked in Opera and it works fine. Same for IE and
Firefox - all current versions. It's only missing in Chrome.

[image: Inline image 2]
ᐧ

Best regards,

Martin Dimmock
Owner,
HarryAdney Internet Services

Tel: 01969 662794
Email: martin@harryadney.co.uk
Web: http://harryadney.co.uk

http://www.peopleperhour.com/hire/me/1709457307/45006?next=http%3A%2F%2Fwww.peopleperhour.com%2Ffreelancer%2Fmartin%2Fweb-host-domain-name-registrar-we%2F45006

http://customer.heartinternet.uk/aff.cgi?entry=TpX6bAcwY3UTTrgMm_vk/w&landing=web_hosting

http://www.linkedin.com/in/martindimmock

**Comment by TeamwSynapseIndia** [comment] 2015-04-20 13:10
Hi battlemidget ,

Could you please let me know the issue and how you fixed it?

**Comment by adam-stokes** [comment] 2015-04-20 13:12
This was fixed in https://github.com/battlemidget/hexo-theme-striped/commit/9ae47902cc2179c9e42005c7e09ddb23da6b860c
